<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action' => '动作',
    'Are you sure you want to delete this item?' => '',
    'Create' => '创建',
    'Create Menu' => '创建菜单',
    'Create Wechat Action' => '创建动作',
    'Create Wechat Menu' => '创建微信菜单',
    'Delete' => '',
    'Get Menu From Wechat' => '',
    'Gh ID' => '',
    'Import Menu From Wechat' => '从微信服务器导入菜单',
    'Keyword' => '关键词',
    'Mwx Actions' => '',
    'Mwx Menus' => '',
    'Parent ID' => '父菜单',
    'Reset' => '',
    'Save Menu From Wechat' => '保存到微信服务器',
    'Search' => '',
    'Sort Order' => '序号',
    'Title' => '标题',
    'Type' => '类型',
    'Update' => '编辑',
    'Update Menu' => '编辑菜单',
    'Url' => '地址(URL)',
    'Wechat Actions' => '微信动作',
    'Wechat Menu' => '微信菜单',
    'Wx Action ID' => '动作ID',
    'Wx Menu ID' => '菜单ID',
];
